### ISSUE TITLE
请教一个关于收藏列表取消收藏的问题

### ISSUE THREAD

**Issue by jhwsx** [wangzailfm/WanAndroidClient#5]
您好,
       

- 我写的是java版本的,遇到一个问题,在收藏列表中,取消收藏后,在文章列表中,仍然是已收藏的状态,刷新后也是如此.我看了几个完整的java版本的项目,也有同样的问题.

  
- 对比了一下,使用Fiddler抓包看了一下,请求时的url,以及post的参数都是一样的,只是我的cookie和你的不一样

      

-  我的cookie是Cookie: loginUserName=xxxxx; loginUserPassword=xxxxxxxx; JSESSIONID=DB79BE078531A9E5BB9F94CD1CCDDFB0
       

- 你的cookie是Cookie: Expires=Tue, 10-Apr-2018 09:37:45 GMT;loginUserName=xxxxxx; Path=/;JSESSIONID=C24100B43ACAE5A3E87B5D6B7FCD283C;loginUserPassword=xxxxxx; HttpOnly
      我是使用的persistentCookieJar这个开源库,通过下面的代码设置的:
```
public static OkHttpClient getOkHttpClient() {
        if (sOkHttpClient == null) {
            synchronized (OkHttpClientManager.class) {
                if (sOkHttpClient == null) {
                    Cache httpCache = new Cache(new File(WanAndroidApplication.getContext().getExternalFilesDir(null), "HttpCache"), 1024 * 1024 * 50);
                    ClearableCookieJar cookieJar =
                            new PersistentCookieJar(new SetCookieCache(), new SharedPrefsCookiePersistor(com.wan.android.util.Utils.getContext()));
                    sOkHttpClient = new OkHttpClient.Builder()
                            .cache(httpCache)
                            .cookieJar(cookieJar)
                            .build();
                }
            }
        }
        return sOkHttpClient;
    }

- 

 ```

- 请问一下,你是怎么实现的,使用java可以利用你的实现方式吗?

**Comment by wangzailfm** [comment]
我的Cookie是在retrofit里面添加的，Java也是可以实现的
